package main

import (
	"github.com/awskendrafrontendservice/mcp-server/config"
	"github.com/awskendrafrontendservice/mcp-server/models"
	tools_x_amz_target_awskendrafrontendservice_deleteindex "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_deleteindex"
	tools_x_amz_target_awskendrafrontendservice_describequerysuggestionsblocklist "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_describequerysuggestionsblocklist"
	tools_x_amz_target_awskendrafrontendservice_deleteaccesscontrolconfiguration "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_deleteaccesscontrolconfiguration"
	tools_x_amz_target_awskendrafrontendservice_putprincipalmapping "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_putprincipalmapping"
	tools_x_amz_target_awskendrafrontendservice_createthesaurus "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_createthesaurus"
	tools_x_amz_target_awskendrafrontendservice_describethesaurus "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_describethesaurus"
	tools_x_amz_target_awskendrafrontendservice_tagresource "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_tagresource"
	tools_x_amz_target_awskendrafrontendservice_describeprincipalmapping "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_describeprincipalmapping"
	tools_x_amz_target_awskendrafrontendservice_createindex "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_createindex"
	tools_x_amz_target_awskendrafrontendservice_associatepersonastoentities "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_associatepersonastoentities"
	tools_x_amz_target_awskendrafrontendservice_getsnapshots "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_getsnapshots"
	tools_x_amz_target_awskendrafrontendservice_describefaq "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_describefaq"
	tools_x_amz_target_awskendrafrontendservice_updateindex "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_updateindex"
	tools_x_amz_target_awskendrafrontendservice_associateentitiestoexperience "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_associateentitiestoexperience"
	tools_x_amz_target_awskendrafrontendservice_updatequerysuggestionsconfig "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_updatequerysuggestionsconfig"
	tools_x_amz_target_awskendrafrontendservice_startdatasourcesyncjob "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_startdatasourcesyncjob"
	tools_x_amz_target_awskendrafrontendservice_createexperience "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_createexperience"
	tools_x_amz_target_awskendrafrontendservice_updatefeaturedresultsset "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_updatefeaturedresultsset"
	tools_x_amz_target_awskendrafrontendservice_clearquerysuggestions "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_clearquerysuggestions"
	tools_x_amz_target_awskendrafrontendservice_updatedatasource "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_updatedatasource"
	tools_x_amz_target_awskendrafrontendservice_listindices "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listindices"
	tools_x_amz_target_awskendrafrontendservice_listfaqs "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listfaqs"
	tools_x_amz_target_awskendrafrontendservice_describeexperience "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_describeexperience"
	tools_x_amz_target_awskendrafrontendservice_listdatasources "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listdatasources"
	tools_x_amz_target_awskendrafrontendservice_listquerysuggestionsblocklists "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listquerysuggestionsblocklists"
	tools_x_amz_target_awskendrafrontendservice_updatethesaurus "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_updatethesaurus"
	tools_x_amz_target_awskendrafrontendservice_listexperiences "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listexperiences"
	tools_x_amz_target_awskendrafrontendservice_createdatasource "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_createdatasource"
	tools_x_amz_target_awskendrafrontendservice_deleteprincipalmapping "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_deleteprincipalmapping"
	tools_x_amz_target_awskendrafrontendservice_query "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_query"
	tools_x_amz_target_awskendrafrontendservice_listdatasourcesyncjobs "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listdatasourcesyncjobs"
	tools_x_amz_target_awskendrafrontendservice_describeindex "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_describeindex"
	tools_x_amz_target_awskendrafrontendservice_batchdeletedocument "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_batchdeletedocument"
	tools_x_amz_target_awskendrafrontendservice_untagresource "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_untagresource"
	tools_x_amz_target_awskendrafrontendservice_createaccesscontrolconfiguration "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_createaccesscontrolconfiguration"
	tools_x_amz_target_awskendrafrontendservice_retrieve "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_retrieve"
	tools_x_amz_target_awskendrafrontendservice_batchdeletefeaturedresultsset "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_batchdeletefeaturedresultsset"
	tools_x_amz_target_awskendrafrontendservice_stopdatasourcesyncjob "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_stopdatasourcesyncjob"
	tools_x_amz_target_awskendrafrontendservice_updateaccesscontrolconfiguration "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_updateaccesscontrolconfiguration"
	tools_x_amz_target_awskendrafrontendservice_describedatasource "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_describedatasource"
	tools_x_amz_target_awskendrafrontendservice_batchputdocument "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_batchputdocument"
	tools_x_amz_target_awskendrafrontendservice_listfeaturedresultssets "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listfeaturedresultssets"
	tools_x_amz_target_awskendrafrontendservice_createfeaturedresultsset "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_createfeaturedresultsset"
	tools_x_amz_target_awskendrafrontendservice_batchgetdocumentstatus "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_batchgetdocumentstatus"
	tools_x_amz_target_awskendrafrontendservice_createquerysuggestionsblocklist "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_createquerysuggestionsblocklist"
	tools_x_amz_target_awskendrafrontendservice_listentitypersonas "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listentitypersonas"
	tools_x_amz_target_awskendrafrontendservice_deletequerysuggestionsblocklist "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_deletequerysuggestionsblocklist"
	tools_x_amz_target_awskendrafrontendservice_listtagsforresource "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listtagsforresource"
	tools_x_amz_target_awskendrafrontendservice_listaccesscontrolconfigurations "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listaccesscontrolconfigurations"
	tools_x_amz_target_awskendrafrontendservice_disassociatepersonasfromentities "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_disassociatepersonasfromentities"
	tools_x_amz_target_awskendrafrontendservice_describefeaturedresultsset "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_describefeaturedresultsset"
	tools_x_amz_target_awskendrafrontendservice_updatequerysuggestionsblocklist "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_updatequerysuggestionsblocklist"
	tools_x_amz_target_awskendrafrontendservice_deletedatasource "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_deletedatasource"
	tools_x_amz_target_awskendrafrontendservice_createfaq "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_createfaq"
	tools_x_amz_target_awskendrafrontendservice_deleteexperience "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_deleteexperience"
	tools_x_amz_target_awskendrafrontendservice_listgroupsolderthanorderingid "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listgroupsolderthanorderingid"
	tools_x_amz_target_awskendrafrontendservice_describequerysuggestionsconfig "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_describequerysuggestionsconfig"
	tools_x_amz_target_awskendrafrontendservice_deletethesaurus "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_deletethesaurus"
	tools_x_amz_target_awskendrafrontendservice_listthesauri "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listthesauri"
	tools_x_amz_target_awskendrafrontendservice_describeaccesscontrolconfiguration "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_describeaccesscontrolconfiguration"
	tools_x_amz_target_awskendrafrontendservice_deletefaq "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_deletefaq"
	tools_x_amz_target_awskendrafrontendservice_listexperienceentities "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_listexperienceentities"
	tools_x_amz_target_awskendrafrontendservice_submitfeedback "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_submitfeedback"
	tools_x_amz_target_awskendrafrontendservice_updateexperience "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_updateexperience"
	tools_x_amz_target_awskendrafrontendservice_getquerysuggestions "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_getquerysuggestions"
	tools_x_amz_target_awskendrafrontendservice_disassociateentitiesfromexperience "github.com/awskendrafrontendservice/mcp-server/tools/x_amz_target_awskendrafrontendservice_disassociateentitiesfromexperience"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_awskendrafrontendservice_deleteindex.CreateDeleteindexTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_describequerysuggestionsblocklist.CreateDescribequerysuggestionsblocklistTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_deleteaccesscontrolconfiguration.CreateDeleteaccesscontrolconfigurationTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_putprincipalmapping.CreatePutprincipalmappingTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_createthesaurus.CreateCreatethesaurusTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_describethesaurus.CreateDescribethesaurusTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_describeprincipalmapping.CreateDescribeprincipalmappingTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_createindex.CreateCreateindexTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_associatepersonastoentities.CreateAssociatepersonastoentitiesTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_getsnapshots.CreateGetsnapshotsTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_describefaq.CreateDescribefaqTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_updateindex.CreateUpdateindexTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_associateentitiestoexperience.CreateAssociateentitiestoexperienceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_updatequerysuggestionsconfig.CreateUpdatequerysuggestionsconfigTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_startdatasourcesyncjob.CreateStartdatasourcesyncjobTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_createexperience.CreateCreateexperienceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_updatefeaturedresultsset.CreateUpdatefeaturedresultssetTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_clearquerysuggestions.CreateClearquerysuggestionsTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_updatedatasource.CreateUpdatedatasourceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listindices.CreateListindicesTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listfaqs.CreateListfaqsTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_describeexperience.CreateDescribeexperienceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listdatasources.CreateListdatasourcesTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listquerysuggestionsblocklists.CreateListquerysuggestionsblocklistsTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_updatethesaurus.CreateUpdatethesaurusTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listexperiences.CreateListexperiencesTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_createdatasource.CreateCreatedatasourceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_deleteprincipalmapping.CreateDeleteprincipalmappingTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_query.CreateQueryTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listdatasourcesyncjobs.CreateListdatasourcesyncjobsTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_describeindex.CreateDescribeindexTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_batchdeletedocument.CreateBatchdeletedocumentTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_createaccesscontrolconfiguration.CreateCreateaccesscontrolconfigurationTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_retrieve.CreateRetrieveTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_batchdeletefeaturedresultsset.CreateBatchdeletefeaturedresultssetTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_stopdatasourcesyncjob.CreateStopdatasourcesyncjobTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_updateaccesscontrolconfiguration.CreateUpdateaccesscontrolconfigurationTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_describedatasource.CreateDescribedatasourceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_batchputdocument.CreateBatchputdocumentTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listfeaturedresultssets.CreateListfeaturedresultssetsTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_createfeaturedresultsset.CreateCreatefeaturedresultssetTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_batchgetdocumentstatus.CreateBatchgetdocumentstatusTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_createquerysuggestionsblocklist.CreateCreatequerysuggestionsblocklistTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listentitypersonas.CreateListentitypersonasTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_deletequerysuggestionsblocklist.CreateDeletequerysuggestionsblocklistTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listtagsforresource.CreateListtagsforresourceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listaccesscontrolconfigurations.CreateListaccesscontrolconfigurationsTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_disassociatepersonasfromentities.CreateDisassociatepersonasfromentitiesTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_describefeaturedresultsset.CreateDescribefeaturedresultssetTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_updatequerysuggestionsblocklist.CreateUpdatequerysuggestionsblocklistTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_deletedatasource.CreateDeletedatasourceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_createfaq.CreateCreatefaqTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_deleteexperience.CreateDeleteexperienceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listgroupsolderthanorderingid.CreateListgroupsolderthanorderingidTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_describequerysuggestionsconfig.CreateDescribequerysuggestionsconfigTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_deletethesaurus.CreateDeletethesaurusTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listthesauri.CreateListthesauriTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_describeaccesscontrolconfiguration.CreateDescribeaccesscontrolconfigurationTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_deletefaq.CreateDeletefaqTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_listexperienceentities.CreateListexperienceentitiesTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_submitfeedback.CreateSubmitfeedbackTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_updateexperience.CreateUpdateexperienceTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_getquerysuggestions.CreateGetquerysuggestionsTool(cfg),
		tools_x_amz_target_awskendrafrontendservice_disassociateentitiesfromexperience.CreateDisassociateentitiesfromexperienceTool(cfg),
	}
}
